### ISSUE TITLE
Table with multiple rows wanted to find out the length(no) of rows in each page

### ISSUE THREAD

**Issue by alpriya87** [Georgegriff/query-selector-shadow-dom#26]
How to find out the length of rows: 
I have 10 rows in a page each of these have multiple column cells 
1. I wanted to find the no of rows in each page programmatically using deepquery selector
2. I have a column that has date, how do i find if they are arranged in descending order from top to bottom using deep query selector 

here is the screen for the same :
![Screen Shot 2020-03-17 at 4 26 12 PM](https://user-images.githubusercontent.com/60447297/76903757-955edc00-686c-11ea-97b5-fa3509c1113e.png)

**Comment by Georgegriff** [comment]
1. my guess to find the number of rows would be to use querySelectorAllDeep('mat-row') and then check the .length of the arrow returned.

2. to check this could you do something simple like finding the first row like this https://www.w3schools.com/cssref/sel_first-of-type.asp `mat-row:first-of-type <<insert-date-column-selector>>`
and then get last row like https://www.w3schools.com/cssref/sel_last-of-type.asp `mat-row:last-of-type <<insert-date-column-selector>>` 

You could then compare the values i'm not sure.


Because this isn't an issue with the library and more a question on how to work with css selectors in general i'm going to close this issue.
